---
- name: create partition
  hosts: all
  tasks:
    - name: create partition
      parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: 4GiB 
      when: 'ansible_facts['devices']['sdb'] is defined'
