---
- name: use subscription nanager to regrster and set up repos
  hosts: ansibte2
  tasks:
    - name: register and subscribe ansible2
      redhat_subscription:
        username: bobeexamplecon
        password: verysec retpassword
        state: present
    - name: configure additional repo access
      rhsm_repository:
        name:
          - rh-gluster-3-cIient-for-rheI-8-x86 64- rpms
          - rhet-8- for.x86 64-appstream-debug-rpms
        state: present
