---
- name: setup cron job
  hosts: ansiblel
  tasks:
    - name: run a cron job
      cron:
        name: 'write message to file'
        minute: "*/2"
        hour: 8-18
        user: ansible
        job: echo "entry written at $(date)" >> /tmp/cron-keepalive
        cron file: keep-alive-messages
        state: present
