---
- name: denonstrate changed status
  hosts: all
  tasks:
    - name: check local time
      command: date
      register: connand_result
      changed_when: true
    - name : print localtime
      debug:
        var: comand result.stdout
