---
- name: demonstrating the fait module
  hosts: all
  ignore errors: yes
  tasks:
    - name: run a script
      command: echo "hello world"
      register: command_result
    - name: report a failure
      fail:
        msg: the command has failed
      when: "'world' in command result.stdout"
    - name: see if we get here
      debug:
        msg: second task executed
