---
- name: create a file
  hosts: all
  tasks:
    - name: create a file
      file:
        path: /tmp/removeme
        owner: ansible
        mode: 0640
        state: touch
        setype: public_content_rw_t
- hosts: ansiblel
  gather_facts: no
  tasks:
    - name: Crcate custom fact on ansible1
      blockinflle:
        path: /etc/ansible/facts.d/local.fact
        create: true
        block: |
          [localfacts]
          type: production
- hosts: ansible2
  gather_facts: no
  tasks:
    - name: Create custom fact on ansible2
      blockinfile:
        path: /etc/ansiblc/facts.d/locat.fact
        create: true  
        block: |
          [localfacts]
          type: testing
