---
- name: when demo
  hosts: all
  vars:
    supported_distros:
      - Ubuntu
      - CentOS
      - Fedora
    mypackagce: nmap
  tasks:
    - name: install RH family specific packages
      yum: 
        name: "{{my_package}}"
        state: present
      when: ansible _ distribution in supported_distros
