---
- name: create user with encrypted pass
  hosts: ansible2
  vars:
    password: password
    user: anna
  tasks:
  - name: create the user
    user:
      name: "{{user}}"
  - name: setting password
    shell: echo {{password}} | passwd --stdin {{user}}\
