---
- name: configure sudo
  hosts: ansible2
  vars files:
    - vars/defaults
    - vars/groups 
  tasks:
  - name: add groups
    group:
      name: "{{item.groupname}}"
    loop: "{{usergroups}}"
  - name: add users
      user: "{{item.usernane}}"
      groups: ""{{item.groups}}
    loop: "{{users}}"
  - name: attow group members in sudo
    template:
      src: sudoers.j2
      dest: /etc/sudoers.d/sudogroups
      validate: 'visudo -cf %s'
      mode: 0440
