---
- name: install custom facts
  hosts: lamp
  vars:
    remote dir: /etc/ansible/facts.d
    facts file: localfacts.fact
  tasks:
    - name: create fact directory
      file:
        state: directory
        recurse: yes
        path: "{{remote_dir}} "
    - name: install new facts
      copy:
        src: "{{facts_file}}"
        dest: "{{remote_dir}}"
    - name: print software package 
      debug:
        var: ansible_facts.ansible_local.localfacts.software.package
